### ISSUE TITLE
Modify hospital importer to download all hospitals for a country

### ISSUE THREAD

**Issue by fmarani** [HospitalAid/hospitalaid#9]
We need to modify `main/utils/dataimport/healthsites.py` and the import_hospital management command to search by Country rather than free text. Please see https://healthsites.io/api/docs/#api-v2-facilities-list

**Comment by jeff303** [comment]
Yeah this is the API call that had the issue I reported to them already.  Will try again today, but it seems there is no actual way to invoke this API as documented.

**Comment by jeff303** [comment]
The issue was fixed: healthsites/healthsites#1411, but it's not clear to me:

1. When this will be available in the production site (which still seems to have the old one)
1. How to use this to search for health sites within a country.  There appear to be two complete incongruent APIs (one to search by term - for autocomplete purposes, and another to list, which includes a country filter but has no capability to query).  I have [asked](https://gitter.im/healthsites/healthsites?at=5eb02fb9adb0ec5c2be3e8c0) on their gitter and will update if I get a response.

**Comment by fmarani** [comment]
Let's download all the hospital for a country. After this, we can do the query as a separate step on the local data.

**Comment by fmarani** [comment]
I am going to close this ticket as the purpose for this was to use an "official" list of verified hospitals, to get missing info (in our system). 

With the latest code, lat/lng is calculated through a geocoder, therefore the healthsites dataset becomes less pressing for us.
